modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mixins]]
config = "alpinewhispers-neoforge.mixins.json"

[[mods]]
modId = "alpinewhispers"
version = "${version}"
displayName = "[Let's Do] Alpinewhispers"
authors = "satisfy"
description = '''
Alpinewhispers brings cozy, arolla_pine furniture to every corner of your world.
'''
logoFile = "pack.png"

[[dependencies.alpinewhispers]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alpinewhispers]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alpinewhispers]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"