modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mods]]
modId = "hearth_and_haven"
version = "${version}"
displayName = "[Let's Do] Hearth & Haven"
authors = "satisfy"
description = '''
Hearth & Haven brings cozy, rustic furniture to every corner of your world.
'''
logoFile = "pack.png"

[[dependencies.hearth_and_haven]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hearth_and_haven]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hearth_and_haven]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"